spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/devstudy}
    username: ${DATABASE_USERNAME:devstudy}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false

server:
  port: ${PORT:8081}
